import { HostileDescriptor } from "./hostile";

const LIGHTRED = 0xe14141;
const RED = 0xe14141; //0x7a213a;
const WHITE = 0xffffff;
const GREEN = 0x39855a;
const LIGHTGREEN = 0x83e04c;
const LIGHTCYAN = 0xdcff70;
const BROWN = 0xffa070; //0x753939;
const BLUE = 0x2980b9;
const LIGHTBLUE = 0x3898ff;
const TEAL = 0x6eeeff;
const LIGHTGREY = 0xb2bcc2;
const LIGHTMAGENTA = 0xbf3fb3;
const YELLOW = 0xffbf36;
const MAGENTA = 0x682b82;
const CYAN = 0x83e04c;

// based on bcrawl/dungeon crawl stone soup stats
export const HOSTILE_DESCS: HostileDescriptor[] = [
  {
    name: "worker ant",
    attack: 8,
    defence: 4,
    color: RED,
    healthPoints: 165,
    character: "a",
    experienceModifier: 10,
  },
  {
    name: "queen ant",
    attack: 20,
    defence: 14,
    color: LIGHTRED,
    healthPoints: 715,
    character: "a",
    experienceModifier: 10,
  },
  {
    name: "soldier ant",
    attack: 20,
    defence: 12,
    color: WHITE,
    healthPoints: 250,
    character: "a",
    experienceModifier: 10,
  },
  {
    name: "formicid",
    attack: 15,
    defence: 3,
    color: GREEN,
    healthPoints: 420,
    character: "a",
    experienceModifier: 10,
  },
  {
    name: "entropy weaver",
    attack: 17,
    defence: 7,
    color: LIGHTCYAN,
    healthPoints: 715,
    character: "a",
    experienceModifier: 10,
  },
  {
    name: "bat",
    attack: 1,
    defence: 1,
    color: LIGHTGREY,
    healthPoints: 35,
    character: "b",
    experienceModifier: 4,
  },
  {
    name: "fire bat",
    attack: 6,
    defence: 1,
    color: LIGHTRED,
    healthPoints: 225,
    character: "b",
    experienceModifier: 8,
  },
  {
    name: "bennu",
    attack: 27,
    defence: 6,
    color: YELLOW,
    healthPoints: 770,
    character: "b",
    experienceModifier: 0,
  },
  {
    name: "caustic shrike",
    attack: 36,
    defence: 8,
    color: LIGHTGREEN,
    healthPoints: 1080,
    character: "b",
    experienceModifier: 15,
  },
  {
    name: "shard shrike",
    attack: 21,
    defence: 2,
    color: LIGHTBLUE,
    healthPoints: 1050,
    character: "b",
    experienceModifier: 12,
  },
  {
    name: "centaur",
    attack: 10,
    defence: 3,
    color: BROWN,
    healthPoints: 220,
    character: "c",
    experienceModifier: 10,
  },
  {
    name: "centaur warrior",
    attack: 16,
    defence: 4,
    color: YELLOW,
    healthPoints: 550,
    character: "c",
    experienceModifier: 12,
  },
  {
    name: "yaktaur",
    attack: 20,
    defence: 4,
    color: RED,
    healthPoints: 440,
    character: "c",
    experienceModifier: 9,
  },
  {
    name: "yaktaur captain",
    attack: 30,
    defence: 5,
    color: LIGHTRED,
    healthPoints: 770,
    character: "c",
    experienceModifier: 9,
  },
  {
    name: "faun",
    attack: 23,
    defence: 2,
    color: GREEN,
    healthPoints: 500,
    character: "c",
    experienceModifier: 8,
  },
  {
    name: "satyr",
    attack: 25,
    defence: 2,
    color: LIGHTGREEN,
    healthPoints: 660,
    character: "c",
    experienceModifier: 10,
  },
  {
    name: "black draconian",
    attack: 20,
    defence: 9,
    color: BLUE,
    healthPoints: 980,
    character: "d",
    experienceModifier: 10,
  },
  {
    name: "yellow draconian",
    attack: 20,
    defence: 9,
    color: YELLOW,
    healthPoints: 980,
    character: "d",
    experienceModifier: 10,
  },
  {
    name: "green draconian",
    attack: 20,
    defence: 9,
    color: GREEN,
    healthPoints: 980,
    character: "d",
    experienceModifier: 10,
  },
  {
    name: "purple draconian",
    attack: 20,
    defence: 8,
    color: MAGENTA,
    healthPoints: 980,
    character: "d",
    experienceModifier: 10,
  },
  {
    name: "red draconian",
    attack: 20,
    defence: 9,
    color: LIGHTRED,
    healthPoints: 980,
    character: "d",
    experienceModifier: 10,
  },
  {
    name: "white draconian",
    attack: 20,
    defence: 9,
    color: WHITE,
    healthPoints: 980,
    character: "d",
    experienceModifier: 10,
  },
  {
    name: "grey draconian",
    attack: 25,
    defence: 16,
    color: LIGHTGREY,
    healthPoints: 980,
    character: "d",
    experienceModifier: 10,
  },
  {
    name: "draconian monk",
    attack: 35,
    defence: -3,
    color: BLUE,
    healthPoints: 1200,
    character: "q",
    experienceModifier: 10,
  },
  {
    name: "draconian shifter",
    attack: 15,
    defence: -1,
    color: LIGHTCYAN,
    healthPoints: 960,
    character: "q",
    experienceModifier: 10,
  },
  {
    name: "draconian annihilator",
    attack: 15,
    defence: -1,
    color: LIGHTBLUE,
    healthPoints: 800,
    character: "q",
    experienceModifier: 10,
  },
  {
    name: "draconian knight",
    attack: 27,
    defence: 3,
    color: CYAN,
    healthPoints: 1120,
    character: "q",
    experienceModifier: 10,
  },
  {
    name: "draconian scorcher",
    attack: 15,
    defence: -1,
    color: LIGHTRED,
    healthPoints: 800,
    character: "q",
    experienceModifier: 10,
  },
  {
    name: "elf",
    attack: 10,
    defence: 3,
    color: LIGHTRED,
    healthPoints: 360,
    character: "e",
    experienceModifier: 10,
  },
  {
    name: "deep elf high priest",
    attack: 14,
    defence: 3,
    color: LIGHTGREEN,
    healthPoints: 495,
    character: "e",
    experienceModifier: 15,
  },
  {
    name: "wandering mushroom",
    attack: 20,
    defence: 5,
    color: BROWN,
    healthPoints: 440,
    character: "f",
    experienceModifier: 10,
  },
  {
    name: "deathcap",
    attack: 33,
    defence: 5,
    color: LIGHTMAGENTA,
    healthPoints: 520,
    character: "f",
    experienceModifier: 6,
  },
  {
    name: "thorn hunter",
    attack: 27,
    defence: 9,
    color: WHITE,
    healthPoints: 975,
    character: "f",
    experienceModifier: 14,
  },
  {
    name: "shambling mangrove",
    attack: 41,
    defence: 13,
    color: LIGHTRED,
    healthPoints: 910,
    character: "f",
    experienceModifier: 12,
  },
  {
    name: "vine stalker",
    attack: 10,
    defence: 2,
    color: GREEN,
    healthPoints: 360,
    character: "f",
    experienceModifier: 10,
  },
  {
    name: "hobgoblin",
    attack: 5,
    defence: 2,
    color: BROWN,
    healthPoints: 55,
    character: "g",
    experienceModifier: 10,
  },
  {
    name: "gnoll",
    attack: 9,
    defence: 2,
    color: YELLOW,
    healthPoints: 130,
    character: "g",
    experienceModifier: 10,
  },
  {
    name: "gnoll shaman",
    attack: 10,
    defence: 2,
    color: WHITE,
    healthPoints: 195,
    character: "g",
    experienceModifier: 10,
  },
  {
    name: "gnoll sergeant",
    attack: 11,
    defence: 2,
    color: CYAN,
    healthPoints: 260,
    character: "g",
    experienceModifier: 10,
  },
  {
    name: "deep dwarf",
    attack: 10,
    defence: 2,
    color: LIGHTBLUE,
    healthPoints: 275,
    character: "g",
    experienceModifier: 10,
  },
  {
    name: "jackal",
    attack: 3,
    defence: 2,
    color: BROWN,
    healthPoints: 55,
    character: "h",
    experienceModifier: 10,
  },
  {
    name: "hound",
    attack: 6,
    defence: 2,
    color: YELLOW,
    healthPoints: 165,
    character: "h",
    experienceModifier: 10,
  },
  {
    name: "howler monkey",
    attack: 8,
    defence: 1,
    color: LIGHTGREEN,
    healthPoints: 185,
    character: "h",
    experienceModifier: 15,
  },
  {
    name: "warg",
    attack: 18,
    defence: 4,
    color: WHITE,
    healthPoints: 325,
    character: "h",
    experienceModifier: 12,
  },
  {
    name: "wolf",
    attack: 12,
    defence: 4,
    color: LIGHTGREY,
    healthPoints: 220,
    character: "h",
    experienceModifier: 12,
  },
  {
    name: "hog",
    attack: 14,
    defence: 2,
    color: LIGHTMAGENTA,
    healthPoints: 330,
    character: "h",
    experienceModifier: 10,
  },
  {
    name: "hell hound",
    attack: 13,
    defence: 6,
    color: CYAN,
    healthPoints: 275,
    character: "h",
    experienceModifier: 10,
  },
  {
    name: "doom hound",
    attack: 45,
    defence: 6,
    color: GREEN,
    healthPoints: 1100,
    character: "h",
    experienceModifier: 10,
  },
  {
    name: "raiju",
    attack: 11,
    defence: 4,
    color: LIGHTCYAN,
    healthPoints: 385,
    character: "h",
    experienceModifier: 12,
  },
  {
    name: "hell hog",
    attack: 20,
    defence: 2,
    color: LIGHTRED,
    healthPoints: 595,
    character: "h",
    experienceModifier: 10,
  },
  {
    name: "polar bear",
    attack: 20,
    defence: 7,
    color: LIGHTBLUE,
    healthPoints: 455,
    character: "h",
    experienceModifier: 12,
  },
  {
    name: "black bear",
    attack: 15,
    defence: 2,
    color: BLUE,
    healthPoints: 270,
    character: "h",
    experienceModifier: 9,
  },
  {
    name: "spriggan",
    attack: 15,
    defence: 1,
    color: LIGHTGREY,
    healthPoints: 245,
    character: "i",
    experienceModifier: 10,
  },
  {
    name: "spriggan druid",
    attack: 18,
    defence: 1,
    color: GREEN,
    healthPoints: 440,
    character: "i",
    experienceModifier: 10,
  },
  {
    name: "spriggan berserker",
    attack: 27,
    defence: 2,
    color: LIGHTRED,
    healthPoints: 540,
    character: "i",
    experienceModifier: 10,
  },
  {
    name: "spriggan air mage",
    attack: 16,
    defence: 1,
    color: LIGHTCYAN,
    healthPoints: 490,
    character: "i",
    experienceModifier: 10,
  },
  {
    name: "spriggan defender",
    attack: 30,
    defence: 3,
    color: YELLOW,
    healthPoints: 675,
    character: "i",
    experienceModifier: 10,
  },
  {
    name: "swamp drake",
    attack: 20,
    defence: 3,
    color: BROWN,
    healthPoints: 300,
    character: "k",
    experienceModifier: 20,
  },
  {
    name: "rime drake",
    attack: 14,
    defence: 3,
    color: BLUE,
    healthPoints: 330,
    character: "k",
    experienceModifier: 22,
  },
  {
    name: "wind drake",
    attack: 14,
    defence: 3,
    color: WHITE,
    healthPoints: 600,
    character: "k",
    experienceModifier: 6,
  },
  {
    name: "lindwurm",
    attack: 20,
    defence: 8,
    color: LIGHTRED,
    healthPoints: 495,
    character: "k",
    experienceModifier: 13,
  },
  {
    name: "death drake",
    attack: 18,
    defence: 6,
    color: LIGHTGREY,
    healthPoints: 765,
    character: "k",
    experienceModifier: 10,
  },
  {
    name: "leopard gecko",
    attack: 5,
    defence: 1,
    color: YELLOW,
    healthPoints: 55,
    character: "l",
    experienceModifier: 16,
  },
  {
    name: "iguana",
    attack: 15,
    defence: 5,
    color: BLUE,
    healthPoints: 165,
    character: "l",
    experienceModifier: 13,
  },
  {
    name: "basilisk",
    attack: 20,
    defence: 3,
    color: MAGENTA,
    healthPoints: 360,
    character: "l",
    experienceModifier: 10,
  },
  {
    name: "wyvern",
    attack: 20,
    defence: 5,
    color: LIGHTGREEN,
    healthPoints: 275,
    character: "l",
    experienceModifier: 15,
  },
  {
    name: "komodo dragon",
    attack: 34,
    defence: 7,
    color: LIGHTRED,
    healthPoints: 440,
    character: "l",
    experienceModifier: 10,
  },
  {
    name: "merfolk",
    attack: 22,
    defence: 4,
    color: LIGHTRED,
    healthPoints: 550,
    character: "m",
    experienceModifier: 4,
  },
  {
    name: "merfolk siren",
    attack: 19,
    defence: 4,
    color: CYAN,
    healthPoints: 405,
    character: "m",
    experienceModifier: 10,
  },
  {
    name: "water nymph",
    attack: 12,
    defence: 2,
    color: MAGENTA,
    healthPoints: 400,
    character: "m",
    experienceModifier: 10,
  },
  {
    name: "bog body",
    attack: 25,
    defence: 1,
    color: GREEN,
    healthPoints: 390,
    character: "n",
    experienceModifier: 16,
  },
  {
    name: "necrophage",
    attack: 8,
    defence: 2,
    color: LIGHTGREY,
    healthPoints: 275,
    character: "n",
    experienceModifier: 12,
  },
  {
    name: "ghoul",
    attack: 30,
    defence: 4,
    color: RED,
    healthPoints: 1470,
    character: "n",
    experienceModifier: 10,
  },
  {
    name: "orc",
    attack: 5,
    defence: 0,
    color: LIGHTRED,
    healthPoints: 70,
    character: "o",
    experienceModifier: 15,
  },
  {
    name: "orc wizard",
    attack: 5,
    defence: 1,
    color: MAGENTA,
    healthPoints: 150,
    character: "o",
    experienceModifier: 10,
  },
  {
    name: "orc priest",
    attack: 6,
    defence: 1,
    color: GREEN,
    healthPoints: 150,
    character: "o",
    experienceModifier: 10,
  },
  {
    name: "orc knight",
    attack: 25,
    defence: 2,
    color: CYAN,
    healthPoints: 675,
    character: "o",
    experienceModifier: 9,
  },
  {
    name: "orc warlord",
    attack: 32,
    defence: 3,
    color: LIGHTCYAN,
    healthPoints: 1125,
    character: "o",
    experienceModifier: 11,
  },
  {
    name: "orc sorcerer",
    attack: 7,
    defence: 5,
    color: LIGHTMAGENTA,
    healthPoints: 315,
    character: "o",
    experienceModifier: 12,
  },
  {
    name: "orc high priest",
    attack: 7,
    defence: 1,
    color: LIGHTGREEN,
    healthPoints: 550,
    character: "o",
    experienceModifier: 10,
  },
  // {
  //   name: "human",
  //   attack: 10,
  //   defence: 3,
  //   color: LIGHTGREY,
  //   healthPoints: 330,
  //   character: "p",
  //   experienceModifier: 10,
  // },
  {
    name: "slave",
    attack: 10,
    defence: 2,
    color: WHITE,
    healthPoints: 275,
    character: "p",
    experienceModifier: 10,
  },
  {
    name: "death knight",
    attack: 28,
    defence: 2,
    color: GREEN,
    healthPoints: 800,
    character: "p",
    experienceModifier: 12,
  },
  {
    name: "vault guard",
    attack: 25,
    defence: 1,
    color: CYAN,
    healthPoints: 715,
    character: "p",
    experienceModifier: 10,
  },
  {
    name: "vault sentinel",
    attack: 15,
    defence: 1,
    color: LIGHTBLUE,
    healthPoints: 520,
    character: "p",
    experienceModifier: 10,
  },
  {
    name: "vault warden",
    attack: 36,
    defence: 1,
    color: LIGHTRED,
    healthPoints: 880,
    character: "p",
    experienceModifier: 12,
  },
  {
    name: "imperial myrmidon",
    attack: 30,
    defence: 1,
    color: LIGHTCYAN,
    healthPoints: 750,
    character: "p",
    experienceModifier: 12,
  },
  {
    name: "servant of whispers",
    attack: 10,
    defence: 1,
    color: BLUE,
    healthPoints: 800,
    character: "p",
    experienceModifier: 10,
  },
  {
    name: "ironheart beastmaster",
    attack: 30,
    defence: 1,
    color: BROWN,
    healthPoints: 550,
    character: "p",
    experienceModifier: 10,
  },
  {
    name: "Killer Klown",
    attack: 30,
    defence: 10,
    color: MAGENTA,
    healthPoints: 1500,
    character: "p",
    experienceModifier: 17,
  },
  {
    name: "rat",
    attack: 3,
    defence: 1,
    color: BROWN,
    healthPoints: 25,
    character: "r",
    experienceModifier: 1,
  },
  {
    name: "quokka",
    attack: 5,
    defence: 2,
    color: WHITE,
    healthPoints: 55,
    character: "r",
    experienceModifier: 10,
  },
  {
    name: "river rat",
    attack: 10,
    defence: 5,
    color: LIGHTGREEN,
    healthPoints: 110,
    character: "r",
    experienceModifier: 13,
  },
  {
    name: "hell rat",
    attack: 20,
    defence: 7,
    color: LIGHTRED,
    healthPoints: 165,
    character: "r",
    experienceModifier: 10,
  },
  {
    name: "porcupine",
    attack: 16,
    defence: 2,
    color: BLUE,
    healthPoints: 160,
    character: "r",
    experienceModifier: 26,
  },
  {
    name: "giant cockroach",
    attack: 2,
    defence: 3,
    color: BROWN,
    healthPoints: 50,
    character: "s",
    experienceModifier: 10,
  },
  {
    name: "scorpion",
    attack: 10,
    defence: 5,
    color: YELLOW,
    healthPoints: 180,
    character: "s",
    experienceModifier: 13,
  },
  {
    name: "emperor scorpion",
    attack: 30,
    defence: 20,
    color: LIGHTGREY,
    healthPoints: 1190,
    character: "s",
    experienceModifier: 13,
  },
  {
    name: "death scarab",
    attack: 33,
    defence: 7,
    color: BLUE,
    healthPoints: 320,
    character: "s",
    experienceModifier: 12,
  },
  {
    name: "tarantella",
    attack: 19,
    defence: 3,
    color: LIGHTMAGENTA,
    healthPoints: 280,
    character: "s",
    experienceModifier: 6,
  },
  {
    name: "jumping spider",
    attack: 20,
    defence: 6,
    color: LIGHTBLUE,
    healthPoints: 320,
    character: "s",
    experienceModifier: 8,
  },
  {
    name: "wolf spider",
    attack: 25,
    defence: 3,
    color: WHITE,
    healthPoints: 550,
    character: "s",
    experienceModifier: 4,
  },
  {
    name: "redback",
    attack: 18,
    defence: 2,
    color: LIGHTRED,
    healthPoints: 270,
    character: "s",
    experienceModifier: 5,
  },
  {
    name: "demonic crawler",
    attack: 16,
    defence: 10,
    color: LIGHTGREEN,
    healthPoints: 585,
    character: "s",
    experienceModifier: 4,
  },
  {
    name: "orb spider",
    attack: 5,
    defence: 3,
    color: MAGENTA,
    healthPoints: 420,
    character: "s",
    experienceModifier: 20,
  },
  {
    name: "crocodile",
    attack: 20,
    defence: 4,
    color: BROWN,
    healthPoints: 275,
    character: "t",
    experienceModifier: 16,
  },
  {
    name: "alligator",
    attack: 30,
    defence: 5,
    color: LIGHTBLUE,
    healthPoints: 720,
    character: "t",
    experienceModifier: 10,
  },
  {
    name: "snapping turtle",
    attack: 30,
    defence: 16,
    color: GREEN,
    healthPoints: 600,
    character: "t",
    experienceModifier: 10,
  },
  {
    name: "alligator snapping turtle",
    attack: 50,
    defence: 19,
    color: LIGHTGREEN,
    healthPoints: 1440,
    character: "t",
    experienceModifier: 10,
  },
  {
    name: "fire crab",
    attack: 15,
    defence: 9,
    color: LIGHTRED,
    healthPoints: 520,
    character: "t",
    experienceModifier: 25,
  },
  {
    name: "ghost crab",
    attack: 20,
    defence: 9,
    color: LIGHTGREY,
    healthPoints: 585,
    character: "t",
    experienceModifier: 25,
  },
  {
    name: "apocalypse crab",
    attack: 15,
    defence: 11,
    color: WHITE,
    healthPoints: 520,
    character: "t",
    experienceModifier: 13,
  },
  {
    name: "ugly thing",
    attack: 17,
    defence: 4,
    color: MAGENTA,
    healthPoints: 660,
    character: "u",
    experienceModifier: 6,
  },
  {
    name: "very ugly thing",
    attack: 27,
    defence: 6,
    color: MAGENTA,
    healthPoints: 990,
    character: "u",
    experienceModifier: 10,
  },
  {
    name: "will-o-wisp",
    attack: 12,
    defence: 4,
    color: LIGHTGREY,
    healthPoints: 180,
    character: "v",
    experienceModifier: 8,
  },
  {
    name: "worm",
    attack: 12,
    defence: 1,
    color: LIGHTRED,
    healthPoints: 180,
    character: "w",
    experienceModifier: 3,
  },
  {
    name: "swamp worm",
    attack: 26,
    defence: 3,
    color: BROWN,
    healthPoints: 350,
    character: "w",
    experienceModifier: 3,
  },
  {
    name: "tyrant leech",
    attack: 35,
    defence: 5,
    color: RED,
    healthPoints: 600,
    character: "w",
    experienceModifier: 8,
  },
  {
    name: "dart slug",
    attack: 3,
    defence: 1,
    color: CYAN,
    healthPoints: 100,
    character: "w",
    experienceModifier: 40,
  },
  {
    name: "torpor snail",
    attack: 25,
    defence: 8,
    color: GREEN,
    healthPoints: 600,
    character: "w",
    experienceModifier: 20,
  },
  {
    name: "elephant slug",
    attack: 40,
    defence: 2,
    color: WHITE,
    healthPoints: 1300,
    character: "w",
    experienceModifier: 2,
  },
  {
    name: "unseen horror",
    attack: 12,
    defence: 5,
    color: MAGENTA,
    healthPoints: 385,
    character: "x",
    experienceModifier: 12,
  },
  {
    name: "ancient zyme",
    attack: 16,
    defence: 6,
    color: GREEN,
    healthPoints: 520,
    character: "x",
    experienceModifier: 8,
  },
  {
    name: "worldbinder",
    attack: 8,
    defence: 12,
    color: CYAN,
    healthPoints: 400,
    character: "x",
    experienceModifier: 13,
  },
  {
    name: "killer bee",
    attack: 10,
    defence: 2,
    color: BROWN,
    healthPoints: 165,
    character: "y",
    experienceModifier: 11,
  },
  {
    name: "queen bee",
    attack: 20,
    defence: 10,
    color: LIGHTMAGENTA,
    healthPoints: 385,
    character: "y",
    experienceModifier: 14,
  },
  {
    name: "vampire mosquito",
    attack: 13,
    defence: 2,
    color: LIGHTGREY,
    healthPoints: 275,
    character: "y",
    experienceModifier: 10,
  },
  {
    name: "hornet",
    attack: 18,
    defence: 6,
    color: YELLOW,
    healthPoints: 330,
    character: "y",
    experienceModifier: 13,
  },
  {
    name: "meliai",
    attack: 14,
    defence: 2,
    color: GREEN,
    healthPoints: 245,
    character: "y",
    experienceModifier: 6,
  },
  {
    name: "spark wasp",
    attack: 33,
    defence: 9,
    color: LIGHTCYAN,
    healthPoints: 660,
    character: "y",
    experienceModifier: 12,
  },
  {
    name: "ghost moth",
    attack: 18,
    defence: 8,
    color: MAGENTA,
    healthPoints: 715,
    character: "y",
    experienceModifier: 18,
  },
  {
    name: "wight",
    attack: 8,
    defence: 4,
    color: GREEN,
    healthPoints: 165,
    character: "z",
    experienceModifier: 16,
  },
  {
    name: "skeletal warrior",
    attack: 25,
    defence: 15,
    color: CYAN,
    healthPoints: 650,
    character: "z",
    experienceModifier: 10,
  },
  {
    name: "ancient champion",
    attack: 50,
    defence: 15,
    color: LIGHTCYAN,
    healthPoints: 700,
    character: "z",
    experienceModifier: 24,
  },
  {
    name: "flying skull",
    attack: 14,
    defence: 10,
    color: WHITE,
    healthPoints: 210,
    character: "z",
    experienceModifier: 10,
  },
  {
    name: "angel",
    attack: 25,
    defence: 10,
    color: WHITE,
    healthPoints: 1020,
    character: "A",
    experienceModifier: 10,
  },
  {
    name: "cherub",
    attack: 15,
    defence: 10,
    color: LIGHTBLUE,
    healthPoints: 765,
    character: "A",
    experienceModifier: 10,
  },
  {
    name: "seraph",
    attack: 50,
    defence: 10,
    color: LIGHTMAGENTA,
    healthPoints: 2125,
    character: "A",
    experienceModifier: 10,
  },
  {
    name: "daeva",
    attack: 25,
    defence: 10,
    color: YELLOW,
    healthPoints: 1190,
    character: "A",
    experienceModifier: 12,
  },
  {
    name: "profane servitor",
    attack: 25,
    defence: 10,
    color: RED,
    healthPoints: 1530,
    character: "A",
    experienceModifier: 10,
  },
  {
    name: "cyclops",
    attack: 35,
    defence: 5,
    color: YELLOW,
    healthPoints: 495,
    character: "C",
    experienceModifier: 17,
  },
  {
    name: "ettin",
    attack: 45,
    defence: 9,
    color: BROWN,
    healthPoints: 660,
    character: "C",
    experienceModifier: 12,
  },
  {
    name: "fire giant",
    attack: 30,
    defence: 8,
    color: RED,
    healthPoints: 960,
    character: "C",
    experienceModifier: 13,
  },
  {
    name: "frost giant",
    attack: 35,
    defence: 9,
    color: LIGHTBLUE,
    healthPoints: 1040,
    character: "C",
    experienceModifier: 11,
  },
  {
    name: "stone giant",
    attack: 45,
    defence: 12,
    color: LIGHTGREY,
    healthPoints: 880,
    character: "C",
    experienceModifier: 10,
  },
  {
    name: "titan",
    attack: 55,
    defence: 10,
    color: MAGENTA,
    healthPoints: 1100,
    character: "C",
    experienceModifier: 12,
  },
  {
    name: "juggernaut",
    attack: 80,
    defence: 20,
    color: LIGHTGREEN,
    healthPoints: 2500,
    character: "C",
    experienceModifier: 12,
  },
  {
    name: "iron giant",
    attack: 65,
    defence: 18,
    color: CYAN,
    healthPoints: 1800,
    character: "C",
    experienceModifier: 10,
  },
  {
    name: "fire dragon",
    attack: 20,
    defence: 10,
    color: LIGHTRED,
    healthPoints: 900,
    character: "D",
    experienceModifier: 12,
  },
  {
    name: "ice dragon",
    attack: 17,
    defence: 10,
    color: WHITE,
    healthPoints: 900,
    character: "D",
    experienceModifier: 10,
  },
  {
    name: "steam dragon",
    attack: 12,
    defence: 5,
    color: BLUE,
    healthPoints: 300,
    character: "D",
    experienceModifier: 29,
  },
  {
    name: "swamp dragon",
    attack: 20,
    defence: 7,
    color: BROWN,
    healthPoints: 675,
    character: "D",
    experienceModifier: 11,
  },
  {
    name: "acid dragon",
    attack: 15,
    defence: 5,
    color: GREEN,
    healthPoints: 275,
    character: "D",
    experienceModifier: 16,
  },
  {
    name: "quicksilver dragon",
    attack: 25,
    defence: 10,
    color: LIGHTCYAN,
    healthPoints: 880,
    character: "D",
    experienceModifier: 14,
  },
  {
    name: "iron dragon",
    attack: 40,
    defence: 20,
    color: CYAN,
    healthPoints: 1170,
    character: "D",
    experienceModifier: 14,
  },
  {
    name: "storm dragon",
    attack: 25,
    defence: 13,
    color: LIGHTBLUE,
    healthPoints: 1050,
    character: "D",
    experienceModifier: 13,
  },
  {
    name: "golden dragon",
    attack: 40,
    defence: 15,
    color: YELLOW,
    healthPoints: 1530,
    character: "D",
    experienceModifier: 26,
  },
  {
    name: "shadow dragon",
    attack: 25,
    defence: 15,
    color: MAGENTA,
    healthPoints: 1275,
    character: "D",
    experienceModifier: 12,
  },
  {
    name: "bone dragon",
    attack: 30,
    defence: 20,
    color: LIGHTGREY,
    healthPoints: 1800,
    character: "D",
    experienceModifier: 12,
  },
  {
    name: "pearl dragon",
    attack: 35,
    defence: 10,
    color: YELLOW,
    healthPoints: 1170,
    character: "D",
    experienceModifier: 16,
  },
  {
    name: "earth elemental",
    attack: 40,
    defence: 14,
    color: BROWN,
    healthPoints: 450,
    character: "E",
    experienceModifier: 13,
  },
  {
    name: "water elemental",
    attack: 22,
    defence: 4,
    color: BLUE,
    healthPoints: 420,
    character: "E",
    experienceModifier: 12,
  },
  {
    name: "air elemental",
    attack: 15,
    defence: 2,
    color: WHITE,
    healthPoints: 330,
    character: "E",
    experienceModifier: 6,
  },
  {
    name: "iron elemental",
    attack: 40,
    defence: 20,
    color: WHITE,
    healthPoints: 1080,
    character: "E",
    experienceModifier: 13,
  },
  {
    name: "cane toad",
    attack: 26,
    defence: 6,
    color: YELLOW,
    healthPoints: 385,
    character: "F",
    experienceModifier: 16,
  },
  {
    name: "goliath frog",
    attack: 30,
    defence: 15,
    color: LIGHTGREY,
    healthPoints: 600,
    character: "F",
    experienceModifier: 10,
  },
  {
    name: "hippogriff",
    attack: 12,
    defence: 2,
    color: BROWN,
    healthPoints: 435,
    character: "H",
    experienceModifier: 8,
  },
  {
    name: "manticore",
    attack: 26,
    defence: 5,
    color: RED,
    healthPoints: 495,
    character: "H",
    experienceModifier: 10,
  },
  {
    name: "minotaur",
    attack: 35,
    defence: 6,
    color: LIGHTRED,
    healthPoints: 780,
    character: "H",
    experienceModifier: 10,
  },
  {
    name: "sphinx",
    attack: 25,
    defence: 5,
    color: LIGHTGREY,
    healthPoints: 880,
    character: "H",
    experienceModifier: 12,
  },
  {
    name: "harpy",
    attack: 19,
    defence: 2,
    color: GREEN,
    healthPoints: 385,
    character: "H",
    experienceModifier: 9,
  },
  {
    name: "mutant beast",
    attack: 27,
    defence: 8,
    color: MAGENTA,
    healthPoints: 825,
    character: "H",
    experienceModifier: 11,
  },
  {
    name: "ancestor",
    attack: 27,
    defence: 5,
    color: LIGHTCYAN,
    healthPoints: 1,
    character: "R",
    experienceModifier: 1,
  },
  {
    name: "knight",
    attack: 27,
    defence: 5,
    color: LIGHTCYAN,
    healthPoints: 1,
    character: "R",
    experienceModifier: 1,
  },
  {
    name: "battlemage",
    attack: 27,
    defence: 5,
    color: LIGHTCYAN,
    healthPoints: 1,
    character: "R",
    experienceModifier: 1,
  },
  {
    name: "hexer",
    attack: 27,
    defence: 5,
    color: LIGHTCYAN,
    healthPoints: 1,
    character: "R",
    experienceModifier: 1,
  },
  {
    name: "ooze",
    attack: 5,
    defence: 1,
    color: LIGHTGREY,
    healthPoints: 120,
    character: "J",
    experienceModifier: 3,
  },
  {
    name: "slime creature",
    attack: 22,
    defence: 1,
    color: GREEN,
    healthPoints: 605,
    character: "J",
    experienceModifier: 3,
  },
  {
    name: "kobold",
    attack: 4,
    defence: 2,
    color: BROWN,
    healthPoints: 35,
    character: "K",
    experienceModifier: 10,
  },
  {
    name: "big kobold",
    attack: 7,
    defence: 3,
    color: YELLOW,
    healthPoints: 275,
    character: "K",
    experienceModifier: 7,
  },
  {
    name: "kobold demonologist",
    attack: 4,
    defence: 2,
    color: MAGENTA,
    healthPoints: 390,
    character: "K",
    experienceModifier: 18,
  },
  {
    name: "lich",
    attack: 20,
    defence: 10,
    color: LIGHTGREY,
    healthPoints: 800,
    character: "L",
    experienceModifier: 18,
  },
  {
    name: "ancient lich",
    attack: 25,
    defence: 20,
    color: WHITE,
    healthPoints: 1080,
    character: "L",
    experienceModifier: 24,
  },
  {
    name: "revenant",
    attack: 26,
    defence: 8,
    color: CYAN,
    healthPoints: 810,
    character: "L",
    experienceModifier: 18,
  },
  {
    name: "halazid warlock",
    attack: 20,
    defence: 8,
    color: GREEN,
    healthPoints: 750,
    character: "L",
    experienceModifier: 10,
  },
  {
    name: "mummy",
    attack: 20,
    defence: 3,
    color: LIGHTGREY,
    healthPoints: 195,
    character: "M",
    experienceModifier: 21,
  },
  {
    name: "guardian mummy",
    attack: 30,
    defence: 6,
    color: YELLOW,
    healthPoints: 455,
    character: "M",
    experienceModifier: 13,
  },
  {
    name: "greater mummy",
    attack: 35,
    defence: 10,
    color: WHITE,
    healthPoints: 1950,
    character: "M",
    experienceModifier: 24,
  },
  {
    name: "mummy priest",
    attack: 30,
    defence: 8,
    color: RED,
    healthPoints: 650,
    character: "M",
    experienceModifier: 20,
  },
  {
    name: "naga",
    attack: 17,
    defence: 6,
    color: GREEN,
    healthPoints: 275,
    character: "N",
    experienceModifier: 13,
  },
  {
    name: "naga mage",
    attack: 17,
    defence: 6,
    color: MAGENTA,
    healthPoints: 385,
    character: "N",
    experienceModifier: 14,
  },
  {
    name: "naga sharpshooter",
    attack: 17,
    defence: 6,
    color: LIGHTGREY,
    healthPoints: 720,
    character: "N",
    experienceModifier: 14,
  },
  {
    name: "naga ritualist",
    attack: 14,
    defence: 6,
    color: BROWN,
    healthPoints: 600,
    character: "N",
    experienceModifier: 14,
  },
  {
    name: "naga warrior",
    attack: 28,
    defence: 6,
    color: BLUE,
    healthPoints: 1000,
    character: "N",
    experienceModifier: 11,
  },
  {
    name: "nagaraja",
    attack: 27,
    defence: 6,
    color: LIGHTMAGENTA,
    healthPoints: 825,
    character: "N",
    experienceModifier: 15,
  },
  {
    name: "ogre",
    attack: 17,
    defence: 1,
    color: BROWN,
    healthPoints: 275,
    character: "O",
    experienceModifier: 9,
  },
  {
    name: "two-headed ogre",
    attack: 20,
    defence: 3,
    color: LIGHTRED,
    healthPoints: 550,
    character: "O",
    experienceModifier: 15,
  },
  {
    name: "ogre mage",
    attack: 12,
    defence: 1,
    color: MAGENTA,
    healthPoints: 550,
    character: "O",
    experienceModifier: 16,
  },
  {
    name: "tengu",
    attack: 10,
    defence: 2,
    color: LIGHTBLUE,
    healthPoints: 225,
    character: "Q",
    experienceModifier: 10,
  },
  {
    name: "tengu conjurer",
    attack: 10,
    defence: 2,
    color: BLUE,
    healthPoints: 315,
    character: "Q",
    experienceModifier: 13,
  },
  {
    name: "tengu warrior",
    attack: 16,
    defence: 2,
    color: CYAN,
    healthPoints: 600,
    character: "Q",
    experienceModifier: 13,
  },
  {
    name: "tengu reaver",
    attack: 27,
    defence: 2,
    color: LIGHTMAGENTA,
    healthPoints: 850,
    character: "Q",
    experienceModifier: 13,
  },
  {
    name: "efreet",
    attack: 17,
    defence: 10,
    color: RED,
    healthPoints: 385,
    character: "R",
    experienceModifier: 12,
  },
  {
    name: "rakshasa",
    attack: 20,
    defence: 6,
    color: YELLOW,
    healthPoints: 660,
    character: "R",
    experienceModifier: 15,
  },
  {
    name: "dryad",
    attack: 10,
    defence: 6,
    color: LIGHTGREEN,
    healthPoints: 520,
    character: "R",
    experienceModifier: 10,
  },
  {
    name: "adder",
    attack: 5,
    defence: 1,
    color: LIGHTGREEN,
    healthPoints: 110,
    character: "S",
    experienceModifier: 10,
  },
  {
    name: "water moccasin",
    attack: 10,
    defence: 2,
    color: BROWN,
    healthPoints: 275,
    character: "S",
    experienceModifier: 11,
  },
  {
    name: "black mamba",
    attack: 20,
    defence: 4,
    color: BLUE,
    healthPoints: 385,
    character: "S",
    experienceModifier: 12,
  },
  {
    name: "sea snake",
    attack: 26,
    defence: 2,
    color: LIGHTCYAN,
    healthPoints: 650,
    character: "S",
    experienceModifier: 10,
  },
  {
    name: "anaconda",
    attack: 6,
    defence: 4,
    color: LIGHTGREY,
    healthPoints: 605,
    character: "S",
    experienceModifier: 10,
  },
  {
    name: "guardian serpent",
    attack: 26,
    defence: 6,
    color: WHITE,
    healthPoints: 440,
    character: "S",
    experienceModifier: 10,
  },
  {
    name: "shock serpent",
    attack: 20,
    defence: 2,
    color: LIGHTBLUE,
    healthPoints: 550,
    character: "S",
    experienceModifier: 12,
  },
  {
    name: "mana viper",
    attack: 23,
    defence: 3,
    color: MAGENTA,
    healthPoints: 495,
    character: "S",
    experienceModifier: 10,
  },
  {
    name: "troll",
    attack: 20,
    defence: 3,
    color: BROWN,
    healthPoints: 385,
    character: "T",
    experienceModifier: 10,
  },
  {
    name: "iron troll",
    attack: 40,
    defence: 20,
    color: CYAN,
    healthPoints: 880,
    character: "T",
    experienceModifier: 10,
  },
  {
    name: "deep troll",
    attack: 30,
    defence: 10,
    color: YELLOW,
    healthPoints: 700,
    character: "T",
    experienceModifier: 9,
  },
  {
    name: "deep troll earth mage",
    attack: 27,
    defence: 12,
    color: MAGENTA,
    healthPoints: 480,
    character: "T",
    experienceModifier: 10,
  },
  {
    name: "deep troll shaman",
    attack: 27,
    defence: 8,
    color: WHITE,
    healthPoints: 480,
    character: "T",
    experienceModifier: 12,
  },
  {
    name: "vampire",
    attack: 15,
    defence: 10,
    color: RED,
    healthPoints: 330,
    character: "V",
    experienceModifier: 11,
  },
  {
    name: "vampire knight",
    attack: 33,
    defence: 10,
    color: CYAN,
    healthPoints: 715,
    character: "V",
    experienceModifier: 16,
  },
  {
    name: "vampire mage",
    attack: 15,
    defence: 10,
    color: MAGENTA,
    healthPoints: 550,
    character: "V",
    experienceModifier: 15,
  },
  {
    name: "jiangshi",
    attack: 27,
    defence: 10,
    color: YELLOW,
    healthPoints: 650,
    character: "V",
    experienceModifier: 10,
  },
  {
    name: "phantom",
    attack: 10,
    defence: 3,
    color: BLUE,
    healthPoints: 385,
    character: "W",
    experienceModifier: 5,
  },
  {
    name: "shadow",
    attack: 14,
    defence: 7,
    color: MAGENTA,
    healthPoints: 240,
    character: "W",
    experienceModifier: 18,
  },
  {
    name: "silent spectre",
    attack: 15,
    defence: 5,
    color: CYAN,
    healthPoints: 440,
    character: "W",
    experienceModifier: 10,
  },
  {
    name: "wraith",
    attack: 15,
    defence: 10,
    color: LIGHTGREY,
    healthPoints: 330,
    character: "W",
    experienceModifier: 14,
  },
  {
    name: "shadow wraith",
    attack: 35,
    defence: 7,
    color: LIGHTMAGENTA,
    healthPoints: 550,
    character: "W",
    experienceModifier: 15,
  },
  {
    name: "freezing wraith",
    attack: 16,
    defence: 12,
    color: LIGHTBLUE,
    healthPoints: 440,
    character: "W",
    experienceModifier: 10,
  },
  {
    name: "eidolon",
    attack: 35,
    defence: 12,
    color: BROWN,
    healthPoints: 715,
    character: "W",
    experienceModifier: 14,
  },
  {
    name: "phantasmal warrior",
    attack: 39,
    defence: 12,
    color: LIGHTGREEN,
    healthPoints: 495,
    character: "W",
    experienceModifier: 13,
  },
  {
    name: "thrashing horror",
    attack: 17,
    defence: 5,
    color: YELLOW,
    healthPoints: 495,
    character: "X",
    experienceModifier: 10,
  },
  {
    name: "tentacled monstrosity",
    attack: 22,
    defence: 5,
    color: GREEN,
    healthPoints: 1265,
    character: "X",
    experienceModifier: 10,
  },
  {
    name: "Orb Guardian",
    attack: 45,
    defence: 13,
    color: MAGENTA,
    healthPoints: 825,
    character: "X",
    experienceModifier: 20,
  },
  {
    name: "tentacled starspawn",
    attack: 40,
    defence: 5,
    color: LIGHTCYAN,
    healthPoints: 880,
    character: "X",
    experienceModifier: 20,
  },
  {
    name: "starspawn tentacle",
    attack: 3,
    defence: 8,
    color: LIGHTCYAN,
    healthPoints: 220,
    character: "w",
    experienceModifier: 10,
  },
  {
    name: "starcursed mass",
    attack: 16,
    defence: 10,
    color: BLUE,
    healthPoints: 1500,
    character: "X",
    experienceModifier: 12,
  },
  {
    name: "dream sheep",
    attack: 13,
    defence: 2,
    color: CYAN,
    healthPoints: 220,
    character: "Y",
    experienceModifier: 10,
  },
  {
    name: "yak",
    attack: 18,
    defence: 4,
    color: BROWN,
    healthPoints: 385,
    character: "Y",
    experienceModifier: 9,
  },
  {
    name: "death yak",
    attack: 30,
    defence: 9,
    color: YELLOW,
    healthPoints: 770,
    character: "Y",
    experienceModifier: 8,
  },
  {
    name: "catoblepas",
    attack: 36,
    defence: 10,
    color: MAGENTA,
    healthPoints: 770,
    character: "Y",
    experienceModifier: 8,
  },
  {
    name: "elephant",
    attack: 20,
    defence: 8,
    color: GREEN,
    healthPoints: 675,
    character: "Y",
    experienceModifier: 9,
  },
  {
    name: "dire elephant",
    attack: 40,
    defence: 13,
    color: BLUE,
    healthPoints: 1125,
    character: "Y",
    experienceModifier: 8,
  },
  {
    name: "hellephant",
    attack: 45,
    defence: 13,
    color: LIGHTRED,
    healthPoints: 1700,
    character: "Y",
    experienceModifier: 10,
  },
  {
    name: "apis",
    attack: 40,
    defence: 9,
    color: WHITE,
    healthPoints: 1200,
    character: "Y",
    experienceModifier: 8,
  },
  {
    name: "ice beast",
    attack: 5,
    defence: 5,
    color: LIGHTBLUE,
    healthPoints: 275,
    character: "Y",
    experienceModifier: 13,
  },
  {
    name: "sky beast",
    attack: 5,
    defence: 3,
    color: LIGHTCYAN,
    healthPoints: 275,
    character: "Y",
    experienceModifier: 13,
  },
  {
    name: "simulacrum",
    attack: 6,
    defence: 10,
    color: LIGHTBLUE,
    healthPoints: 110,
    character: "Z",
    experienceModifier: 9,
  },
  {
    name: "small simulacrum",
    attack: 6,
    defence: 10,
    color: LIGHTBLUE,
    healthPoints: 110,
    character: "Z",
    experienceModifier: 9,
  },
  {
    name: "large zombie",
    attack: 23,
    defence: 8,
    color: YELLOW,
    healthPoints: 330,
    character: "Z",
    experienceModifier: 9,
  },
  {
    name: "large simulacrum",
    attack: 14,
    defence: 10,
    color: LIGHTCYAN,
    healthPoints: 275,
    character: "Z",
    experienceModifier: 9,
  },
  {
    name: "spectral thing",
    attack: 20,
    defence: 8,
    color: GREEN,
    healthPoints: 440,
    character: "Z",
    experienceModifier: 11,
  },
  {
    name: "kraken",
    attack: 50,
    defence: 20,
    color: LIGHTMAGENTA,
    healthPoints: 2080,
    character: "X",
    experienceModifier: 6,
  },
  {
    name: "tentacle",
    attack: 29,
    defence: 5,
    color: LIGHTMAGENTA,
    healthPoints: 480,
    character: "w",
    experienceModifier: 10,
  },
  {
    name: "octopode",
    attack: 24,
    defence: 1,
    color: LIGHTCYAN,
    healthPoints: 560,
    character: "x",
    experienceModifier: 10,
  },
  {
    name: "lava snake",
    attack: 7,
    defence: 2,
    color: LIGHTRED,
    healthPoints: 165,
    character: "S",
    experienceModifier: 17,
  },
  {
    name: "salamander",
    attack: 17,
    defence: 5,
    color: LIGHTRED,
    healthPoints: 640,
    character: "N",
    experienceModifier: 10,
  },
  {
    name: "salamander mystic",
    attack: 10,
    defence: 5,
    color: YELLOW,
    healthPoints: 650,
    character: "N",
    experienceModifier: 10,
  },
  {
    name: "player illusion",
    attack: 5,
    defence: 1,
    color: WHITE,
    healthPoints: 140,
    character: "@",
    experienceModifier: 15,
  },
  {
    name: "dancing weapon",
    attack: 30,
    defence: 10,
    color: MAGENTA,
    healthPoints: 150,
    character: "(",
    experienceModifier: 10,
  },
  {
    name: "spectral weapon",
    attack: 6,
    defence: 5,
    color: GREEN,
    healthPoints: 150,
    character: "(",
    experienceModifier: 11,
  },
  {
    name: "eldritch tentacle",
    attack: 30,
    defence: 13,
    color: MAGENTA,
    healthPoints: 1200,
    character: "w",
    experienceModifier: 10,
  },
  {
    name: "demonspawn",
    attack: 10,
    defence: 3,
    color: BROWN,
    healthPoints: 330,
    character: "6",
    experienceModifier: 10,
  },
  {
    name: "monstrous demonspawn",
    attack: 20,
    defence: 3,
    color: LIGHTGREY,
    healthPoints: 1000,
    character: "6",
    experienceModifier: 10,
  },
  {
    name: "gelid demonspawn",
    attack: 20,
    defence: 6,
    color: BLUE,
    healthPoints: 550,
    character: "6",
    experienceModifier: 10,
  },
  {
    name: "infernal demonspawn",
    attack: 20,
    defence: 6,
    color: RED,
    healthPoints: 550,
    character: "6",
    experienceModifier: 10,
  },
  {
    name: "torturous demonspawn",
    attack: 20,
    defence: 3,
    color: MAGENTA,
    healthPoints: 550,
    character: "6",
    experienceModifier: 10,
  },
  {
    name: "crimson imp",
    attack: 4,
    defence: 3,
    color: RED,
    healthPoints: 135,
    character: "5",
    experienceModifier: 13,
  },
  {
    name: "quasit",
    attack: 3,
    defence: 5,
    color: LIGHTGREY,
    healthPoints: 150,
    character: "5",
    experienceModifier: 13,
  },
  {
    name: "white imp",
    attack: 4,
    defence: 4,
    color: WHITE,
    healthPoints: 110,
    character: "5",
    experienceModifier: 10,
  },
  {
    name: "ufetubus",
    attack: 5,
    defence: 2,
    color: LIGHTCYAN,
    healthPoints: 70,
    character: "5",
    experienceModifier: 28,
  },
  {
    name: "iron imp",
    attack: 12,
    defence: 6,
    color: CYAN,
    healthPoints: 165,
    character: "5",
    experienceModifier: 14,
  },
  {
    name: "shadow imp",
    attack: 6,
    defence: 3,
    color: MAGENTA,
    healthPoints: 110,
    character: "5",
    experienceModifier: 11,
  },
  {
    name: "rust devil",
    attack: 12,
    defence: 10,
    color: BROWN,
    healthPoints: 440,
    character: "4",
    experienceModifier: 15,
  },
  {
    name: "orange demon",
    attack: 15,
    defence: 3,
    color: LIGHTRED,
    healthPoints: 520,
    character: "4",
    experienceModifier: 12,
  },
  {
    name: "red devil",
    attack: 19,
    defence: 7,
    color: RED,
    healthPoints: 315,
    character: "4",
    experienceModifier: 13,
  },
  {
    name: "hellwing",
    attack: 10,
    defence: 16,
    color: LIGHTGREY,
    healthPoints: 455,
    character: "4",
    experienceModifier: 12,
  },
  {
    name: "ice devil",
    attack: 16,
    defence: 12,
    color: WHITE,
    healthPoints: 440,
    character: "4",
    experienceModifier: 11,
  },
  {
    name: "chaos spawn",
    attack: 19,
    defence: 7,
    color: MAGENTA,
    healthPoints: 330,
    character: "4",
    experienceModifier: 12,
  },
  {
    name: "sun demon",
    attack: 30,
    defence: 10,
    color: YELLOW,
    healthPoints: 550,
    character: "3",
    experienceModifier: 14,
  },
  {
    name: "soul eater",
    attack: 25,
    defence: 18,
    color: MAGENTA,
    healthPoints: 605,
    character: "3",
    experienceModifier: 13,
  },
  {
    name: "smoke demon",
    attack: 8,
    defence: 5,
    color: LIGHTGREY,
    healthPoints: 385,
    character: "3",
    experienceModifier: 15,
  },
  {
    name: "neqoxec",
    attack: 15,
    defence: 4,
    color: LIGHTMAGENTA,
    healthPoints: 330,
    character: "3",
    experienceModifier: 12,
  },
  {
    name: "ynoxinul",
    attack: 12,
    defence: 3,
    color: LIGHTCYAN,
    healthPoints: 330,
    character: "3",
    experienceModifier: 13,
  },
  {
    name: "sixfirhy",
    attack: 15,
    defence: 2,
    color: LIGHTBLUE,
    healthPoints: 385,
    character: "3",
    experienceModifier: 6,
  },
  {
    name: "shadow demon",
    attack: 21,
    defence: 7,
    color: MAGENTA,
    healthPoints: 550,
    character: "2",
    experienceModifier: 13,
  },
  {
    name: "green death",
    attack: 32,
    defence: 5,
    color: GREEN,
    healthPoints: 715,
    character: "2",
    experienceModifier: 14,
  },
  {
    name: "blizzard demon",
    attack: 25,
    defence: 10,
    color: LIGHTBLUE,
    healthPoints: 660,
    character: "2",
    experienceModifier: 16,
  },
  {
    name: "balrug",
    attack: 60,
    defence: 5,
    color: RED,
    healthPoints: 770,
    character: "2",
    experienceModifier: 12,
  },
  {
    name: "cacodemon",
    attack: 30,
    defence: 11,
    color: YELLOW,
    healthPoints: 975,
    character: "2",
    experienceModifier: 16,
  },
  {
    name: "hell beast",
    attack: 28,
    defence: 5,
    color: BROWN,
    healthPoints: 840,
    character: "2",
    experienceModifier: 17,
  },
  {
    name: "hellion",
    attack: 10,
    defence: 5,
    color: LIGHTRED,
    healthPoints: 385,
    character: "2",
    experienceModifier: 12,
  },
  {
    name: "reaper",
    attack: 45,
    defence: 15,
    color: LIGHTGREY,
    healthPoints: 770,
    character: "2",
    experienceModifier: 14,
  },
  {
    name: "lorocyproca",
    attack: 40,
    defence: 10,
    color: BLUE,
    healthPoints: 770,
    character: "2",
    experienceModifier: 14,
  },
  {
    name: "tormentor",
    attack: 8,
    defence: 12,
    color: LIGHTMAGENTA,
    healthPoints: 385,
    character: "2",
    experienceModifier: 10,
  },
  {
    name: "Ice Fiend",
    attack: 25,
    defence: 15,
    color: WHITE,
    healthPoints: 990,
    character: "1",
    experienceModifier: 17,
  },
  {
    name: "Shadow Fiend",
    attack: 25,
    defence: 12,
    color: MAGENTA,
    healthPoints: 1050,
    character: "1",
    experienceModifier: 13,
  },
  {
    name: "Hell Sentinel",
    attack: 40,
    defence: 25,
    color: BROWN,
    healthPoints: 1425,
    character: "1",
    experienceModifier: 10,
  },
  {
    name: "Executioner",
    attack: 30,
    defence: 10,
    color: LIGHTGREY,
    healthPoints: 660,
    character: "1",
    experienceModifier: 18,
  },
  {
    name: "Orb Demon",
    attack: 20,
    defence: 10,
    color: LIGHTBLUE,
    healthPoints: 1500,
    character: "1",
    experienceModifier: 15,
  },
  {
    name: "saltling",
    attack: 20,
    defence: 15,
    color: WHITE,
    healthPoints: 270,
    character: "8",
    experienceModifier: 10,
  },
  {
    name: "peacekeeper",
    attack: 25,
    defence: 20,
    color: YELLOW,
    healthPoints: 450,
    character: "8",
    experienceModifier: 10,
  },
  {
    name: "iron golem",
    attack: 35,
    defence: 15,
    color: CYAN,
    healthPoints: 1350,
    character: "8",
    experienceModifier: 10,
  },
  {
    name: "crystal guardian",
    attack: 35,
    defence: 22,
    color: GREEN,
    healthPoints: 640,
    character: "8",
    experienceModifier: 10,
  },
  {
    name: "toenail golem",
    attack: 20,
    defence: 8,
    color: RED,
    healthPoints: 585,
    character: "8",
    experienceModifier: 10,
  },
  {
    name: "electric golem",
    attack: 15,
    defence: 5,
    color: LIGHTCYAN,
    healthPoints: 1350,
    character: "8",
    experienceModifier: 12,
  },
  {
    name: "ushabti",
    attack: 30,
    defence: 9,
    color: BROWN,
    healthPoints: 455,
    character: "8",
    experienceModifier: 10,
  },
  {
    name: "gargoyle",
    attack: 20,
    defence: 18,
    color: LIGHTGREY,
    healthPoints: 270,
    character: "9",
    experienceModifier: 26,
  },
  {
    name: "war gargoyle",
    attack: 30,
    defence: 22,
    color: CYAN,
    healthPoints: 520,
    character: "9",
    experienceModifier: 18,
  },
  {
    name: "molten gargoyle",
    attack: 20,
    defence: 14,
    color: RED,
    healthPoints: 315,
    character: "9",
    experienceModifier: 18,
  },
  {
    name: "pandemonium lord",
    attack: 5,
    defence: 1,
    color: MAGENTA,
    healthPoints: 1710,
    character: "&",
    experienceModifier: 14,
  },
  {
    name: "death cob",
    attack: 35,
    defence: 10,
    color: YELLOW,
    healthPoints: 910,
    character: "z",
    experienceModifier: 10,
  },
  {
    name: "Mennas",
    attack: 30,
    defence: 15,
    color: LIGHTCYAN,
    healthPoints: 1520,
    character: "A",
    experienceModifier: 18,
  },
  {
    name: "Nessos",
    attack: 16,
    defence: 4,
    color: MAGENTA,
    healthPoints: 720,
    character: "c",
    experienceModifier: 18,
  },
  {
    name: "Chuck",
    attack: 45,
    defence: 14,
    color: WHITE,
    healthPoints: 1170,
    character: "C",
    experienceModifier: 10,
  },
  {
    name: "Polyphemus",
    attack: 45,
    defence: 10,
    color: GREEN,
    healthPoints: 1520,
    character: "C",
    experienceModifier: 10,
  },
  {
    name: "Antaeus",
    attack: 75,
    defence: 28,
    color: LIGHTCYAN,
    healthPoints: 6820,
    character: "C",
    experienceModifier: 10,
  },
  {
    name: "Tiamat",
    attack: 60,
    defence: 30,
    color: MAGENTA,
    healthPoints: 3850,
    character: "d",
    experienceModifier: 10,
  },
  {
    name: "Bai Suzhen",
    attack: 24,
    defence: 14,
    color: LIGHTBLUE,
    healthPoints: 1850,
    character: "d",
    experienceModifier: 16,
  },
  {
    name: "Xtahua",
    attack: 40,
    defence: 15,
    color: RED,
    healthPoints: 2200,
    character: "D",
    experienceModifier: 18,
  },
  {
    name: "the Serpent of Hell",
    attack: 35,
    defence: 16,
    color: RED,
    healthPoints: 2805,
    character: "D",
    experienceModifier: 21,
  },
  {
    name: "the Serpent of Hell",
    attack: 35,
    defence: 20,
    color: BLUE,
    healthPoints: 2805,
    character: "D",
    experienceModifier: 21,
  },
  {
    name: "the Serpent of Hell",
    attack: 35,
    defence: 30,
    color: RED,
    healthPoints: 3230,
    character: "D",
    experienceModifier: 16,
  },
  {
    name: "the Serpent of Hell",
    attack: 35,
    defence: 16,
    color: RED,
    healthPoints: 3230,
    character: "D",
    experienceModifier: 18,
  },
  {
    name: "Bai Suzhen",
    attack: 30,
    defence: 22,
    color: YELLOW,
    healthPoints: 1850,
    character: "D",
    experienceModifier: 18,
  },
  {
    name: "Duvessa",
    attack: 10,
    defence: 2,
    color: BLUE,
    healthPoints: 360,
    character: "e",
    experienceModifier: 15,
  },
  {
    name: "Ijyb",
    attack: 4,
    defence: 2,
    color: BLUE,
    healthPoints: 240,
    character: "g",
    experienceModifier: 8,
  },
  {
    name: "Robin",
    attack: 5,
    defence: 1,
    color: LIGHTCYAN,
    healthPoints: 160,
    character: "g",
    experienceModifier: 10,
  },
  {
    name: "Grum",
    attack: 20,
    defence: 2,
    color: LIGHTRED,
    healthPoints: 400,
    character: "g",
    experienceModifier: 19,
  },
  {
    name: "Crazy Yiuf",
    attack: 9,
    defence: 2,
    color: MAGENTA,
    healthPoints: 195,
    character: "g",
    experienceModifier: 10,
  },
  {
    name: "Jorgrun",
    attack: 20,
    defence: 2,
    color: LIGHTMAGENTA,
    healthPoints: 1200,
    character: "g",
    experienceModifier: 18,
  },
  {
    name: "Natasha",
    attack: 10,
    defence: 2,
    color: MAGENTA,
    healthPoints: 150,
    character: "h",
    experienceModifier: 10,
  },
  {
    name: "Arachne",
    attack: 30,
    defence: 3,
    color: LIGHTCYAN,
    healthPoints: 2040,
    character: "H",
    experienceModifier: 10,
  },
  {
    name: "Asterion",
    attack: 35,
    defence: 4,
    color: LIGHTBLUE,
    healthPoints: 1275,
    character: "H",
    experienceModifier: 15,
  },
  {
    name: "the Enchantress",
    attack: 26,
    defence: 1,
    color: LIGHTMAGENTA,
    healthPoints: 975,
    character: "i",
    experienceModifier: 35,
  },
  {
    name: "Sonja",
    attack: 9,
    defence: 2,
    color: RED,
    healthPoints: 300,
    character: "K",
    experienceModifier: 40,
  },
  {
    name: "Menkaure",
    attack: 25,
    defence: 3,
    color: MAGENTA,
    healthPoints: 240,
    character: "M",
    experienceModifier: 48,
  },
  {
    name: "Khufu",
    attack: 35,
    defence: 10,
    color: LIGHTRED,
    healthPoints: 2430,
    character: "M",
    experienceModifier: 20,
  },
  {
    name: "Ilsuiw",
    attack: 10,
    defence: 5,
    color: LIGHTGREEN,
    healthPoints: 1520,
    character: "m",
    experienceModifier: 10,
  },
  {
    name: "Vashnia",
    attack: 25,
    defence: 6,
    color: LIGHTCYAN,
    healthPoints: 1600,
    character: "N",
    experienceModifier: 27,
  },
  {
    name: "Erolcha",
    attack: 20,
    defence: 3,
    color: LIGHTBLUE,
    healthPoints: 540,
    character: "O",
    experienceModifier: 50,
  },
  {
    name: "Urug",
    attack: 30,
    defence: 2,
    color: RED,
    healthPoints: 700,
    character: "o",
    experienceModifier: 14,
  },
  {
    name: "Nergalle",
    attack: 6,
    defence: 9,
    color: WHITE,
    healthPoints: 600,
    character: "o",
    experienceModifier: 12,
  },
  {
    name: "Saint Roka",
    attack: 35,
    defence: 3,
    color: LIGHTBLUE,
    healthPoints: 1980,
    character: "o",
    experienceModifier: 15,
  },
  {
    name: "Sojobo",
    attack: 28,
    defence: 2,
    color: LIGHTGREEN,
    healthPoints: 1500,
    character: "Q",
    experienceModifier: 20,
  },
  {
    name: "Azrael",
    attack: 17,
    defence: 10,
    color: LIGHTRED,
    healthPoints: 880,
    character: "R",
    experienceModifier: 12,
  },
  {
    name: "Mara",
    attack: 30,
    defence: 10,
    color: LIGHTMAGENTA,
    healthPoints: 1440,
    character: "R",
    experienceModifier: 35,
  },
  {
    name: "Aizul",
    attack: 25,
    defence: 8,
    color: LIGHTMAGENTA,
    healthPoints: 1400,
    character: "S",
    experienceModifier: 10,
  },
  {
    name: "Purgy",
    attack: 9,
    defence: 1,
    color: GREEN,
    healthPoints: 350,
    character: "T",
    experienceModifier: 10,
  },
  {
    name: "moon troll",
    attack: 40,
    defence: 20,
    color: LIGHTCYAN,
    healthPoints: 1800,
    character: "T",
    experienceModifier: 10,
  },
  {
    name: "Jory",
    attack: 40,
    defence: 10,
    color: LIGHTRED,
    healthPoints: 1800,
    character: "V",
    experienceModifier: 13,
  },
  {
    name: "Gastronok",
    attack: 40,
    defence: 2,
    color: MAGENTA,
    healthPoints: 1500,
    character: "w",
    experienceModifier: 16,
  },
  {
    name: "Nellie",
    attack: 45,
    defence: 13,
    color: LIGHTMAGENTA,
    healthPoints: 2400,
    character: "Y",
    experienceModifier: 8,
  },
  {
    name: "Murray",
    attack: 20,
    defence: 30,
    color: LIGHTRED,
    healthPoints: 1610,
    character: "z",
    experienceModifier: 15,
  },
  {
    name: "Ignacio",
    attack: 20,
    defence: 10,
    color: LIGHTMAGENTA,
    healthPoints: 2520,
    character: "1",
    experienceModifier: 14,
  },
  {
    name: "Grinder",
    attack: 11,
    defence: 3,
    color: BLUE,
    healthPoints: 390,
    character: "5",
    experienceModifier: 11,
  },
  {
    name: "Donald",
    attack: 26,
    defence: 3,
    color: BLUE,
    healthPoints: 840,
    character: "@",
    experienceModifier: 20,
  },
  {
    name: "Margery",
    attack: 30,
    defence: 4,
    color: LIGHTRED,
    healthPoints: 1650,
    character: "@",
    experienceModifier: 15,
  },
  {
    name: "Maurice",
    attack: 10,
    defence: 1,
    color: GREEN,
    healthPoints: 600,
    character: "@",
    experienceModifier: 24,
  },
  {
    name: "Nikola",
    attack: 20,
    defence: 1,
    color: LIGHTCYAN,
    healthPoints: 1890,
    character: "@",
    experienceModifier: 13,
  },
  {
    name: "Mnoleg",
    attack: 40,
    defence: 10,
    color: LIGHTGREEN,
    healthPoints: 3485,
    character: "&",
    experienceModifier: 15,
  },
  {
    name: "Lom Lobon",
    attack: 40,
    defence: 10,
    color: LIGHTBLUE,
    healthPoints: 3895,
    character: "&",
    experienceModifier: 15,
  },
  {
    name: "Cerebov",
    attack: 60,
    defence: 30,
    color: RED,
    healthPoints: 6510,
    character: "&",
    experienceModifier: 15,
  },
  {
    name: "Gloorx Vloq",
    attack: 45,
    defence: 10,
    color: LIGHTGREY,
    healthPoints: 3520,
    character: "&",
    experienceModifier: 15,
  },
  {
    name: "Geryon",
    attack: 35,
    defence: 15,
    color: GREEN,
    healthPoints: 3000,
    character: "&",
    experienceModifier: 15,
  },
  {
    name: "Dispater",
    attack: 50,
    defence: 40,
    color: MAGENTA,
    healthPoints: 4480,
    character: "&",
    experienceModifier: 15,
  },
  {
    name: "Asmodeus",
    attack: 50,
    defence: 30,
    color: LIGHTRED,
    healthPoints: 4505,
    character: "&",
    experienceModifier: 25,
  },
  {
    name: "Ereshkigal",
    attack: 40,
    defence: 10,
    color: WHITE,
    healthPoints: 3510,
    character: "&",
    experienceModifier: 15,
  },
];
